# Generated by Django 4.2.7 on 2025-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=255)),
                ("planting_date", models.DateField()),
                ("expected_harvest", models.DateField()),
                ("area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("silt", "Silt"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("drip", "Drip"),
                            ("sprinkler", "Sprinkler"),
                            ("surface", "Surface"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "farm_data",
            },
        ),
    ]
