# Generated by Django 4.2.7 on 2025-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
