# Generated by Django 4.2.7 on 2025-10-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0003_product_harvest_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("tractor", "Tractor"),
                            ("harvester", "Harvester"),
                            ("plow", "Plow"),
                            ("sprayer", "Sprayer"),
                            ("seeder", "Seeder"),
                            ("cultivator", "Cultivator"),
                            ("irrigation", "Irrigation System"),
                            ("storage", "Storage Equipment"),
                            ("processing", "Processing Equipment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="equipment/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Under Maintenance"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("condition", models.CharField(blank=True, max_length=100, null=True)),
                ("year_manufactured", models.IntegerField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("min_rental_days", models.IntegerField(default=1)),
                ("max_rental_days", models.IntegerField(blank=True, null=True)),
                ("delivery_available", models.BooleanField(default=False)),
                ("delivery_radius_km", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "equipment",
            },
        ),
        migrations.CreateModel(
            name="EquipmentRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("rental_days", models.IntegerField()),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("delivery_required", models.BooleanField(default=False)),
                ("delivery_address", models.TextField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="marketplace.equipment",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "equipment_rentals",
                "ordering": ["-created_at"],
            },
        ),
    ]
