# Generated by Django 4.2.7 on 2025-10-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_equipment_equipmentrental"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ["-created_at"]},
        ),
    ]
