# Generated by Django 4.2.7 on 2025-11-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0007_productinquiry_message"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productinquiry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productinquiry",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="marketplace.equipment",
            ),
        ),
        migrations.AddField(
            model_name="productinquiry",
            name="inquiry_type",
            field=models.CharField(
                choices=[("product", "Product"), ("equipment", "Equipment")],
                default="product",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productinquiry",
            name="inquirer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productinquiry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="marketplace.product",
            ),
        ),
        migrations.AlterField(
            model_name="productinquiry",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productinquiry",
            unique_together={("product", "inquirer", "equipment")},
        ),
    ]
